//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.10 at 08:31:55 PM CEST 
//


package ch.erebetez.xmlobjects;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}gBlockElements"/>
 *       &lt;attribute name="major" use="required" type="{}stVersion" />
 *       &lt;attribute name="minor" use="required" type="{}stVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "atom",
    "dictionary",
    "list"
})
@XmlRootElement(name = "marshallenvelop")
public class Marshallenvelop {

    protected CtAtom atom;
    protected CtDictionary dictionary;
    protected CtList list;
    @XmlAttribute(name = "major", required = true)
    protected int major;
    @XmlAttribute(name = "minor", required = true)
    protected int minor;

    /**
     * Gets the value of the atom property.
     * 
     * @return
     *     possible object is
     *     {@link CtAtom }
     *     
     */
    public CtAtom getAtom() {
        return atom;
    }

    /**
     * Sets the value of the atom property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtAtom }
     *     
     */
    public void setAtom(CtAtom value) {
        this.atom = value;
    }

    /**
     * Gets the value of the dictionary property.
     * 
     * @return
     *     possible object is
     *     {@link CtDictionary }
     *     
     */
    public CtDictionary getDictionary() {
        return dictionary;
    }

    /**
     * Sets the value of the dictionary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDictionary }
     *     
     */
    public void setDictionary(CtDictionary value) {
        this.dictionary = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link CtList }
     *     
     */
    public CtList getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtList }
     *     
     */
    public void setList(CtList value) {
        this.list = value;
    }

    /**
     * Gets the value of the major property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getMajor() {
        return major;
    }

    /**
     * Sets the value of the major property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMajor(int value) {
        this.major = value;
    }

    /**
     * Gets the value of the minor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getMinor() {
        return minor;
    }

    /**
     * Sets the value of the minor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinor(int value) {
        this.minor = value;
    }

}
