//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.10 at 08:31:55 PM CEST 
//


package ch.erebetez.xmlobjects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CtList }
     * 
     */
    public CtList createCtList() {
        return new CtList();
    }

    /**
     * Create an instance of {@link CtDictionary }
     * 
     */
    public CtDictionary createCtDictionary() {
        return new CtDictionary();
    }

    /**
     * Create an instance of {@link Marshallenvelop }
     * 
     */
    public Marshallenvelop createMarshallenvelop() {
        return new Marshallenvelop();
    }

    /**
     * Create an instance of {@link CtAtom }
     * 
     */
    public CtAtom createCtAtom() {
        return new CtAtom();
    }

    /**
     * Create an instance of {@link CtList.Item }
     * 
     */
    public CtList.Item createCtListItem() {
        return new CtList.Item();
    }

    /**
     * Create an instance of {@link CtDictionary.Member }
     * 
     */
    public CtDictionary.Member createCtDictionaryMember() {
        return new CtDictionary.Member();
    }

}
